### ISSUE TITLE
Theme specific Chrome theme-color

### ISSUE THREAD

**Issue by nervewax** [mkdo/kapow-theme#7]
https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

It could be pulled from the primary colour as a fallback or defined separately if needed?

**Comment by davetgreen** [comment]
@nervewax we can add the meta tag in no problem, we'd just have to look at how we replace the colour. My thinking is that we have a customizer setting for 'Mobile Colour' which is output in the header `<meta name="theme-color" content="<?php echo esc_attr( $mobile_theme_colour ); ?>">.

In fact, that is actually the best way, as it gives the client control, and doesn't required some awkward JS replacement or anything.

Easy win, I'll sort this week.

**Comment by davetgreen** [comment]
@nervewax Your wish is my command. Now a customizer option! 

Completed.

**Comment by mwtsn** [comment]
Yo @davetgreen, there is an argument that this could go into kapow-core

**Comment by davetgreen** [comment]
@mwtsn Possibly yeah, we need to work out what factor leads to a customizer setting being global or theme only.

This also has an impact on the data storage and syntax used, as anything not bound to the theme (so, in Kapow Core) is going to have to use `get_option()` to retrieve, and the setting will need to be registered as `option` rather than `theme_mod`
